# Generated by Django 3.1.3 on 2021-03-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('street_line_1', models.CharField(max_length=255)),
                ('street_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='geolocator',
            name='collected_data',
            field=models.TextField(editable=False, help_text='Appended geolocalization data', null=True),
        ),
        migrations.AlterField(
            model_name='geolocator',
            name='input_ipv4',
            field=models.GenericIPAddressField(default='check', help_text='or:'),
        ),
    ]
